# Generated by Django 5.2.4 on 2025-08-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.BigIntegerField(null=True),
        ),
    ]
